// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplying.proto

package supplying;

public interface SupplyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:supplying.SupplyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
