// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplying.proto

package supplying;

public interface SupplyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:supplying.SupplyRequest)
    com.google.protobuf.MessageOrBuilder {
}
