// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplying.proto

package supplying;

public interface SupplyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:supplying.SupplyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string supplyStatus = 1;</code>
   */
  java.lang.String getSupplyStatus();
  /**
   * <code>string supplyStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getSupplyStatusBytes();
}
