// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplying.proto

package supplying;

public final class SupplyingServiceImpl {
  private SupplyingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supplying_SupplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supplying_SupplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supplying_SupplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supplying_SupplyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017supplying.proto\022\tsupplying\"%\n\rSupplyRe" +
      "quest\022\024\n\014updateStatus\030\001 \001(\t\"&\n\016SupplyRes" +
      "ponse\022\024\n\014supplyStatus\030\001 \001(\t2W\n\020Supplying" +
      "Service\022C\n\014turnOnSupply\022\030.supplying.Supp" +
      "lyRequest\032\031.supplying.SupplyResponseB#\n\t" +
      "supplyingB\024SupplyingServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_supplying_SupplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_supplying_SupplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supplying_SupplyRequest_descriptor,
        new java.lang.String[] { "UpdateStatus", });
    internal_static_supplying_SupplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_supplying_SupplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supplying_SupplyResponse_descriptor,
        new java.lang.String[] { "SupplyStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
