// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplying.proto

package supplying;

public final class SupplyingServiceImpl {
  private SupplyingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supplying_SupplyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supplying_SupplyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_supplying_SupplyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_supplying_SupplyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017supplying.proto\022\tsupplying\"\017\n\rSupplyRe" +
      "quest\"\036\n\016SupplyResponse\022\014\n\004text\030\001 \001(\t2W\n" +
      "\020SupplyingService\022C\n\014turnOnSupply\022\030.supp" +
      "lying.SupplyRequest\032\031.supplying.SupplyRe" +
      "sponseB#\n\tsupplyingB\024SupplyingServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_supplying_SupplyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_supplying_SupplyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supplying_SupplyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_supplying_SupplyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_supplying_SupplyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_supplying_SupplyResponse_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
